### ISSUE TITLE
Create session failed，Could not parse W3C capabilities: 'automationName' Mac2

### ISSUE THREAD

**Issue by wanglinwu2019** [appium/appium-mac2-driver#25]
It is failed when create seesion, whether appium 1.19.1 or appium-desktop 1.19.1-beta.2.
MacOs : 10.15.7
Xcode : 12.2
My desired capabilities are: {'automationName': 'Mac2', 'platformName': 'mac', 'bundleId': 'com.apple.TextEdit'}
**Do I need to build this code with my Xcode? What is the build configuration？**

Full log:
[2020-12-08 08:37:52][HTTP] Waiting until the server is closed
[2020-12-08 08:37:52][HTTP] Received server close event
[2020-12-08 08:37:52][Appium] Welcome to Appium v1.19.1
[2020-12-08 08:37:52][Appium] Non-default server args:
[2020-12-08 08:37:52][Appium] logTimestamp: true
[2020-12-08 08:37:52][Appium] relaxedSecurityEnabled: true
[2020-12-08 08:37:52][Appium] allowInsecure: {
[2020-12-08 08:37:52][Appium] }
[2020-12-08 08:37:52][Appium] denyInsecure: {
[2020-12-08 08:37:52][Appium] }
[2020-12-08 08:37:52][Appium] Appium REST http interface listener started on 0.0.0.0:4723
[2020-12-08 08:38:04][HTTP] Request idempotency key: 221e5129-5a0c-4782-87d7-5e68b9b6799d
[2020-12-08 08:38:04][HTTP] --> POST /wd/hub/session
[2020-12-08 08:38:04][HTTP] {"capabilities":{"firstMatch":[{"appium:automationName":"Mac2","platformName":"mac","appium:bundleId":"com.apple.TextEdit"}]},"desiredCapabilities":{"automationName":"Mac2","platformName":"mac","bundleId":"com.apple.TextEdit"}}
[2020-12-08 08:38:04][W3C] Calling AppiumDriver.createSession() with args: [{"automationName":"Mac2","platformName":"mac","bundleId":"com.apple.TextEdit"},null,{"firstMatch":[{"appium:automationName":"Mac2","platformName":"mac","appium:bundleId":"com.apple.TextEdit"}]}]
[2020-12-08 08:38:04][BaseDriver] Event 'newSessionRequested' logged at 1607431084629 (20:38:04 GMT+0800 (中国标准时间))
**[2020-12-08 08:38:04][Appium] Could not parse W3C capabilities: 'automationName' Mac2 not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter,Safari,Gecko**
[2020-12-08 08:38:04][Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[2020-12-08 08:38:04][BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[2020-12-08 08:38:04][BaseDriver] automationName
[2020-12-08 08:38:04][BaseDriver] bundleId
**[2020-12-08 08:38:04][Appium] Could not parse fixed W3C capabilities: 'automationName' Mac2 not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter,Safari,Gecko. Falling back to JSONWP protocol**
[2020-12-08 08:38:04][BaseDriver] Event 'newSessionStarted' logged at 1607431084636 (20:38:04 GMT+0800 (中国标准时间))
**[2020-12-08 08:38:04][MJSONWP] Encountered internal error running command: Error: Could not find a driver for automationName 'Mac2' and platformName 'mac'. Please check your desired capabilities**
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.getDriverAndVersionForCaps (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:247:11)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:319:66)
[2020-12-08 08:38:04][MJSONWP] at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:15)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:528:26)
[2020-12-08 08:38:04][MJSONWP] at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:300:34)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:439:15
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[2020-12-08 08:38:04][MJSONWP] at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[2020-12-08 08:38:04][MJSONWP] at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[2020-12-08 08:38:04][MJSONWP] at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[2020-12-08 08:38:04][MJSONWP] at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[2020-12-08 08:38:04][MJSONWP] at invokeCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:224:16)
[2020-12-08 08:38:04][MJSONWP] at done (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:213:7)
[2020-12-08 08:38:04][MJSONWP] at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:273:7)
[2020-12-08 08:38:04][MJSONWP] at IncomingMessage.emit (events.js:208:15)
[2020-12-08 08:38:04][MJSONWP] at endReadableNT (_stream_readable.js:1168:12)
[2020-12-08 08:38:04][MJSONWP] at processTicksAndRejections (internal/process/task_queues.js:77:11)
[2020-12-08 08:38:04][MJSONWP] Destroying socket connection
[2020-12-08 08:38:04][HTTP] <-- POST /wd/hub/session 500 55 ms - 249
[2020-12-08 08:38:04][HTTP]
[2020-12-08 08:38:04][HTTP] Request idempotency key: 0c74f816-5e6d-4b47-b0ed-a0658e7b998b
[2020-12-08 08:38:04][HTTP] --> POST /wd/hub/session
[2020-12-08 08:38:04][HTTP] {"capabilities":{"firstMatch":[{"appium:automationName":"Mac2","platformName":"mac","appium:bundleId":"com.apple.TextEdit"}]},"desiredCapabilities":{"automationName":"Mac2","platformName":"mac","bundleId":"com.apple.TextEdit"}}
[2020-12-08 08:38:04][W3C] Calling AppiumDriver.createSession() with args: [{"automationName":"Mac2","platformName":"mac","bundleId":"com.apple.TextEdit"},null,{"firstMatch":[{"appium:automationName":"Mac2","platformName":"mac","appium:bundleId":"com.apple.TextEdit"}]}]
[2020-12-08 08:38:04][BaseDriver] Event 'newSessionRequested' logged at 1607431084765 (20:38:04 GMT+0800 (中国标准时间))
[2020-12-08 08:38:04][Appium] Could not parse W3C capabilities: 'automationName' Mac2 not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter,Safari,Gecko
[2020-12-08 08:38:04][Appium] Trying to fix W3C capabilities by merging them with JSONWP caps
[2020-12-08 08:38:04][BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[2020-12-08 08:38:04][BaseDriver] automationName
[2020-12-08 08:38:04][BaseDriver] bundleId
[2020-12-08 08:38:04][Appium] Could not parse fixed W3C capabilities: 'automationName' Mac2 not part of Appium,UiAutomator2,UiAutomator1,XCUITest,YouiEngine,Espresso,Tizen,Fake,Instruments,Windows,Mac,Flutter,Safari,Gecko. Falling back to JSONWP protocol
[2020-12-08 08:38:04][BaseDriver] Event 'newSessionStarted' logged at 1607431084767 (20:38:04 GMT+0800 (中国标准时间))
[2020-12-08 08:38:04][MJSONWP] Encountered internal error running command: Error: Could not find a driver for automationName 'Mac2' and platformName 'mac'. Please check your desired capabilities
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.getDriverAndVersionForCaps (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:247:11)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.createSession (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:319:66)
[2020-12-08 08:38:04][MJSONWP] at commandExecutor (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:334:9)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:15)
[2020-12-08 08:38:04][MJSONWP] at AppiumDriver.executeCommand (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/lib/appium.js:528:26)
[2020-12-08 08:38:04][MJSONWP] at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:300:34)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:439:15
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[2020-12-08 08:38:04][MJSONWP] at Route.dispatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[2020-12-08 08:38:04][MJSONWP] at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[2020-12-08 08:38:04][MJSONWP] at logger (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
[2020-12-08 08:38:04][MJSONWP] at Layer.handle [as handle_request] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[2020-12-08 08:38:04][MJSONWP] at trim_prefix (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[2020-12-08 08:38:04][MJSONWP] at Function.process_params (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[2020-12-08 08:38:04][MJSONWP] at next (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[2020-12-08 08:38:04][MJSONWP] at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[2020-12-08 08:38:04][MJSONWP] at invokeCallback (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:224:16)
[2020-12-08 08:38:04][MJSONWP] at done (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:213:7)
[2020-12-08 08:38:04][MJSONWP] at IncomingMessage.onEnd (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:273:7)
[2020-12-08 08:38:04][MJSONWP] at IncomingMessage.emit (events.js:208:15)
[2020-12-08 08:38:04][MJSONWP] at endReadableNT (_stream_readable.js:1168:12)
[2020-12-08 08:38:04][MJSONWP] at processTicksAndRejections (internal/process/task_queues.js:77:11)
[2020-12-08 08:38:04][MJSONWP] Destroying socket connection
[2020-12-08 08:38:04][HTTP] <-- POST /wd/hub/session 500 6 ms - 249
[2020-12-08 08:38:04][HTTP]

**Comment by mykola-mokhnach** [comment]
Mac2 driver is only available since version 1.20

**Comment by poliveira-fuze** [comment]
This is still happening with MacOS 11.3.1 with Appium 2.0.0-beta.12.

```
(...)
[Appium] Plugins which can handle cmd 'createSession': images (sessionless)
[Appium] Plugin images (sessionless) is now handling cmd 'createSession'
[Appium] Executing default handling behavior for command 'createSession'
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1628502815270 (10:53:35 GMT+0100 (Western European Summer Time))
[Appium] Could not parse W3C capabilities: 'automationName' can't be blank
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1628502815282 (10:53:35 GMT+0100 (Western European Summer Time))
[debug] [W3C] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
(...)
[HTTP] <-- POST /wd/hub/session 400 78 ms - 3081
```
Any idea what can be causing this? I've added `appium:showServerLogs` to the node configuration but can't see any more additional output.

**Comment by SyedHuzaifaAkbar** [comment]
> This is still happening with MacOS 11.3.1 with Appium 2.0.0-beta.12.
> 
> ```
> (...)
> [Appium] Plugins which can handle cmd 'createSession': images (sessionless)
> [Appium] Plugin images (sessionless) is now handling cmd 'createSession'
> [Appium] Executing default handling behavior for command 'createSession'
> [debug] [BaseDriver] Event 'newSessionRequested' logged at 1628502815270 (10:53:35 GMT+0100 (Western European Summer Time))
> [Appium] Could not parse W3C capabilities: 'automationName' can't be blank
> [debug] [BaseDriver] Event 'newSessionStarted' logged at 1628502815282 (10:53:35 GMT+0100 (Western European Summer Time))
> [debug] [W3C] Encountered internal error running command: InvalidArgumentError: 'automationName' can't be blank
> (...)
> [HTTP] <-- POST /wd/hub/session 400 78 ms - 3081
> ```
> 
> Any idea what can be causing this? I've added `appium:showServerLogs` to the node configuration but can't see any more additional output.

Did you find any solutions?
