### ISSUE TITLE
Starting a new session fails

### ISSUE THREAD

**Issue by PiotrNestor** [appium/appium-mac2-driver#324]
**Problem description:** Starting a session the first time works OK. This session is then stopped. Starting a new session after that fails in the Mac2Driver.

The test sequence is:
 - start driver - this starts the session and launches the application under test
 - verify that application main widow is visible
 - quit driver  - note that this should stop the application but it doesn't. I've added an explicit 'macos: terminateApp'

The first time the above scenario works OK.
Repeating the scenario fails (while 'appium' is running)
'appium' must be restarted to re-run the test. 

**Question:** Any idea how to resolve the issue?

**Details:**
MacOS: Sonoma 14.6.1
Appium v2.13.1
Mac2Driver v1.20.4

**Logs:**
Part of the appium and mac2 driver logs showing the issue
The log is related to the test sequence:
- Stop the tested application with 'terminateApp' (after a successful test)
- Quit driver
- Start new test (starting session, launching app, etc.)

````
[703bbe77][Mac2Driver@9081] Calling AppiumDriver.execute() with args: ["macos:terminateApp",[{"path":"/Applications/Studio 3T.app"}],"703bbe77-3c18-4aae-b548-56417c170e57"]
[703bbe77][Mac2Driver@9081] Executing extension command 'macos:terminateApp'
[703bbe77][WD Proxy] Proxying [POST /wda/apps/terminate] to [POST http://127.0.0.1:10100/session/907FF760-598F-428D-8D0C-0F51F6463596/wda/apps/terminate] with body: {"path":"/Applications/Studio 3T.app"}
[703bbe77][WD Proxy] Got response with status 200: {"value":true,"sessionId":"907FF760-598F-428D-8D0C-0F51F6463596"}
[703bbe77][Mac2Driver@9081] Responding to client with driver.execute() result: true
[703bbe77][HTTP] <-- POST /session/703bbe77-3c18-4aae-b548-56417c170e57/execute/sync 200 1105 ms - 14 
[703bbe77][HTTP] --> DELETE /session/703bbe77-3c18-4aae-b548-56417c170e57 {}
[703bbe77][Mac2Driver@9081] Calling AppiumDriver.deleteSession() with args: ["703bbe77-3c18-4aae-b548-56417c170e57"]
[703bbe77][AppiumDriver@9518] Event 'quitSessionRequested' logged at 1734615048946 (14:30:48 GMT+0100 (Central European Standard Time))
[703bbe77][AppiumDriver@9518] Removing session 703bbe77-3c18-4aae-b548-56417c170e57 from our master session list
[703bbe77][WD Proxy] Matched '/session/907FF760-598F-428D-8D0C-0F51F6463596' to command name 'deleteSession'
[703bbe77][WD Proxy] Proxying [DELETE /session/907FF760-598F-428D-8D0C-0F51F6463596] to [DELETE http://127.0.0.1:10100/session/907FF760-598F-428D-8D0C-0F51F6463596] with no body
[703bbe77][WD Proxy] Got response with status 200: {"value":null,"sessionId":null}
[703bbe77][AppiumDriver@9518] Event 'quitSessionFinished' logged at 1734615048955 (14:30:48 GMT+0100 (Central European Standard Time))
[703bbe77][AppiumDriver@9518] Received response: null
[703bbe77][AppiumDriver@9518] But deleting session, so not returning
[703bbe77][AppiumDriver@9518] Responding to client with driver.deleteSession() result: null
[703bbe77][HTTP] <-- DELETE /session/703bbe77-3c18-4aae-b548-56417c170e57 200 10 ms - 14 
[HTTP] Request idempotency key: aef64ee5-85d6-4fe2-8e5a-74f13c240413
[HTTP] --> POST /session {"capabilities":{"firstMatch":[{"platformName":"mac","appium:automationName":"mac2","appium:appPath":"/Applications/Studio 3T.app"}]}}
[AppiumDriver@9518] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"platformName":"mac","appium:automationName":"mac2","appium:appPath":"/Applications/Studio 3T.app"}]}]
[AppiumDriver@9518] Event 'newSessionRequested' logged at 1734615197747 (14:33:17 GMT+0100 (Central European Standard Time))
[Appium] Attempting to find matching driver for automationName 'mac2' and platformName 'mac'
[Appium] The 'mac2' driver was installed and matched caps.
[Appium] Will require it at /Users/piotr/.appium/node_modules/appium-mac2-driver
[Appium] Requiring driver at /Users/piotr/.appium/node_modules/appium-mac2-driver/build/index.js
[AppiumDriver@9518] Appium v2.13.1 creating new Mac2Driver (v1.20.4) session
[AppiumDriver@9518] Checking BaseDriver versions for Appium and Mac2Driver
[AppiumDriver@9518] Appium's BaseDriver version is 9.13.1
[AppiumDriver@9518] Mac2Driver's BaseDriver version is 9.13.1
[Mac2Driver@4b1e] 
[Mac2Driver@4b1e] Creating session with W3C capabilities: {
  "alwaysMatch": {
    "platformName": "mac",
    "appium:automationName": "mac2",
    "appium:appPath": "/Applications/Studio 3T.app"
  },
  "firstMatch": [
    {}
  ]
}
[c444f145][Mac2Driver@4b1e] Session created with session id: c444f145-110a-4cb7-9dbc-7fbfa0a15c76
[c444f145][WebDriverAgentMac] The host process has already been listening. Proceeding with session creation
[c444f145][WD Proxy] Matched '/session' to command name 'createSession'
[c444f145][WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"mac","automationName":"mac2","appPath":"/Applications/Studio 3T.app"}}}
[c444f145][WD Proxy] Got response with status 500: {"value":{"error":"session not created","message":"Failed to launch '/Applications/Studio 3T.app' application","traceback":""},"sessionId":"C610725B-E80A-4FEA-8CD1-F37277327849"}
[c444f145][W3C] Matched W3C error code 'session not created' to SessionNotCreatedError
[c444f145][WD Proxy] Matched '/session/907FF760-598F-428D-8D0C-0F51F6463596' to command name 'deleteSession'
[c444f145][WD Proxy] Proxying [DELETE /session/907FF760-598F-428D-8D0C-0F51F6463596] to [DELETE http://127.0.0.1:10100/session/907FF760-598F-428D-8D0C-0F51F6463596] with no body
[c444f145][WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x000000019937a2ec __exceptionPreprocess + 176\n\t1   libobjc.A.dylib                     0x0000000198e5e158 objc_exception_throw + 60\n\t2   CoreFoundation                      0x000000019939f268 _CFBundleGetValueForInfoKey + 0\n\t3   WebDriverAgentLib                   0x0000000105b89aa4 -[FBRoute raiseNoSessionException] + 80\n\t4   WebDriverAgentLib                   0x0000000105b899f8 -[FBRoute decorateRequest:] + 244\n\t5   WebDriverAgentLib                   0x0000000105b88e98 -[FBRoute_TargetAction mountRequest:intoResponse:] + 92\n\t6   WebDriverAgentLib                   0x0000000105b81ed0 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 652\n\t7   WebDriverAgentLib                   0x0000000105b7aed8 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t8   WebDriverAgentLib                   0x0000000105b7b920 __72-[RoutingHTTPServer routeMethod:...
[c444f145][W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[c444f145][WebDriverAgentMac] Mac2Driver session cannot be deleted. Original error: Session does not exist
[c444f145][AppiumDriver@9518] Event 'newSessionStarted' logged at 1734615377896 (14:36:17 GMT+0100 (Central European Standard Time))
[c444f145][AppiumDriver@9518] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: Failed to launch '/Applications/Studio 3T.app' application
    at errorFromW3CJsonCode (/Users/piotr/.nvm/versions/node/v22.12.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/piotr/.nvm/versions/node/v22.12.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at WDAMacProxy.command (/Users/piotr/.nvm/versions/node/v22.12.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:348:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at WDAMacServer.startSession (/Users/piotr/.appium/node_modules/appium-mac2-driver/lib/wda-mac.js:448:5)
    at Mac2Driver.createSession (/Users/piotr/.appium/node_modules/appium-mac2-driver/lib/driver.js:120:7)
    at AppiumDriver.createSession (/Users/piotr/.nvm/versions/node/v22.12.0/lib/node_modules/appium/lib/appium.js:740:35)
[c444f145][HTTP] <-- POST /session 500 180158 ms - 1209 
````

**Comment by KazuCocoa** [comment]
What about giving bundle id caps id as well?

**Comment by PiotrNestor** [comment]
I'm not following the suggestion.
The application is a desktop application.
Is a bundle id relevant for this type of application. How to get the bundle id if it exists?

**Comment by KazuCocoa** [comment]
It has several ways:

e.g. `CFBundleIdentifier` in the `Info.plist` for example. Google Chrome is `com.google.Chrome` in `/Applications/Google\ Chrome.app/Contents/Info.plist`.

via apple script:
```
$ osascript -e 'id of app "Google Chrome"'
com.google.Chrome
```

Appium launches the given app with https://developer.apple.com/documentation/xctest/xcuiapplication/2879413-initwithurl, so if your app under test fails to start the process with it, probably the app under test is not good at starting when the process is already running. The system log may provide more insight about the reason for the error.


`appium:bundleId` in https://github.com/appium/appium-mac2-driver
> If it is not provided then the session will be started without an application under test (actually, it will be Finder)

**Comment by PiotrNestor** [comment]
OK, thanks!
The bundle identifier can be extracted for the application using the above commands ...
