### ISSUE TITLE
WebDriverAgentMac unable to create new session when session is already active

### ISSUE THREAD

**Issue by lassebm** [appium/appium-mac2-driver#37]
It could be due to script termination, crashes, etc. Workaround is restart Appium, killing the WebDriverAgentMac process.

Appium: Git 9d8779a22457177644a48d9b8e44cdb127ad161c
Appium Mac2 driver: 0.7.0
macOS: 11.2 Beta 2

Appium log:

```
[debug] [HTTP] Request idempotency key: 14a606d1-565a-4008-9226-7f3c705a75f7
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Mac","appium:automationName":"Mac2","appium:newCommandTimeout":7200,"appium:bundleId":"com.apple.QuickTimePlayerX","appium:showServerLogs":true}]},"desiredCapabilities":{"platformName":"Mac","automationName":"Mac2","newCommandTimeout":7200,"appium:bundleId":"com.apple.QuickTimePlayerX","appium:showServerLogs":true}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Mac","automationName":"Mac2","newCommandTimeout":7200,"appium:bundleId":"com.apple.QuickTimePlayerX","appium:showServerLogs":true},null,{"firstMatch":[{"platformName":"Mac","appium:automationName":"Mac2","appium:newCommandTimeout":7200,"appium:bundleId":"com.apple.QuickTimePlayerX","appium:showServerLogs":true}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1608291566826 (12:39:26 GMT+0100 (Central European Standard Time))
[Appium] Appium v1.20.0-beta.0 creating new Mac2Driver (v0.7.0) session
[Appium] Explicitly enabling use of insecure features:
[Appium]     apple_script
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "Mac",
[debug] [BaseDriver]     "appium:automationName": "Mac2",
[debug] [BaseDriver]     "appium:newCommandTimeout": 7200,
[debug] [BaseDriver]     "appium:bundleId": "com.apple.QuickTimePlayerX",
[debug] [BaseDriver]     "appium:showServerLogs": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: 44850950-b568-40a1-8c84-2bfeabc4bb20
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:10100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"version":"Version 11.2 (Build 20D5029f)"},"ready":true,"build":{"time":"Dec 17 2020 09:52:55"}},"sessionId":"EE5C28BA-644B-4371-8026-0C98C0AB1686"}
[WebDriverAgentMac] The host process has already been listening. Proceeding with session creation
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:10100/session] with body: {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Mac","automationName":"Mac2","newCommandTimeout":7200,"bundleId":"com.apple.QuickTimePlayerX","showServerLogs":true}}}
[debug] [WebDriverAgentMac] [xcodebuild] 2020-12-18 12:39:26.834667+0100 WebDriverAgentRunner-Runner[2044:87730] The data couldn’t be read because it isn’t in the correct format.
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.70s Open com.apple.QuickTimePlayerX
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.70s     Launch com.apple.QuickTimePlayerX
[debug] [WebDriverAgentMac] [xcodebuild] 2020-12-18 12:39:26.838141+0100 WebDriverAgentRunner-Runner[2044:87730] Launching macOS application via NSWorkspace while sandboxed. Launch arguments and environment variables may be dropped.
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.81s         Wait for accessibility to load
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.97s         Setting up automation session
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.98s         Wait for com.apple.QuickTimePlayerX to idle
[debug] [WebDriverAgentMac] [xcodebuild] t =   327.98s Terminate com.apple.QuickTimePlayerX:2095
[WD Proxy] Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff204bc6af __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff201f43c9 objc_exception_throw + 48\n\t2   WebDriverAgentLib                   0x000000010c9baa93 -[FBSession currentApplication] + 243\n\t3   WebDriverAgentLib                   0x000000010c9cdfe7 +[FBSessionCommands currentCapabilities] + 87\n\t4   WebDriverAgentLib                   0x000000010c9cdeb9 +[FBSessionCommands sessionInformation] + 233\n\t5   WebDriverAgentLib                   0x000000010c9ccde5 +[FBSessionCommands handleCreateSession:] + 1813\n\t6   WebDriverAgentLib                   0x000000010c9d1876 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t7   WebDriverAgentLib                   0x000000010c9cb223 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 723\n\t8   WebDriverAgentLib                ...
[debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [WD Proxy] Matched '/session/80FAFC3E-2CF8-4D14-8B66-1C5BC3CCA8C2' to command name 'deleteSession'
[debug] [WD Proxy] Proxying [DELETE /session/80FAFC3E-2CF8-4D14-8B66-1C5BC3CCA8C2] to [DELETE http://127.0.0.1:10100/session/80FAFC3E-2CF8-4D14-8B66-1C5BC3CCA8C2] with no body
[debug] [WebDriverAgentMac] [xcodebuild] 2020-12-18 12:39:28.128569+0100 WebDriverAgentRunner-Runner[2044:87730] The data couldn’t be read because it isn’t in the correct format.
[WD Proxy] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00007fff204bc6af __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff201f43c9 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff204e4a9a -[NSException raise] + 9\n\t3   WebDriverAgentLib                   0x000000010c9d2527 -[FBRoute raiseNoSessionException] + 103\n\t4   WebDriverAgentLib                   0x000000010c9d2456 -[FBRoute decorateRequest:] + 278\n\t5   WebDriverAgentLib                   0x000000010c9d181e -[FBRoute_TargetAction mountRequest:intoResponse:] + 94\n\t6   WebDriverAgentLib                   0x000000010c9cb223 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 723\n\t7   WebDriverAgentLib                   0x000000010c9c487b -[RoutingHTTPServer handleRoute:withRequest:response:] + 219\n\t8   WebDriverAgentLib                   0x000000010c9c5773 __72-[RoutingHTTPServer routeMethod:withPa...
[debug] [W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[WebDriverAgentMac] Mac2Driver session cannot be deleted. Original error: Session does not exist
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1608291568131 (12:39:28 GMT+0100 (Central European Standard Time))
[debug] [W3C] Encountered internal error running command: InvalidElementStateError: The application under test with is not running, possibly crashed
[debug] [W3C]     at errorFromW3CJsonCode (/Users/lmikkelsen/dev/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [W3C]     at ProxyRequestError.getActualError (/Users/lmikkelsen/dev/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [W3C]     at WDAMacProxy.command (/Users/lmikkelsen/dev/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[debug] [W3C]     at runMicrotasks (<anonymous>)
[debug] [W3C]     at processTicksAndRejections (node:internal/process/task_queues:93:5)
[debug] [W3C]     at WDAMacServer.startSession (/Users/lmikkelsen/dev/appium/node_modules/appium-mac2-driver/lib/wda-mac.js:324:5)
[debug] [W3C]     at Mac2Driver.createSession (/Users/lmikkelsen/dev/appium/node_modules/appium-mac2-driver/lib/driver.js:83:7)
[debug] [W3C]     at AppiumDriver.createSession (/Users/lmikkelsen/dev/appium/lib/appium.js:371:35)
[HTTP] <-- POST /wd/hub/session 400 1307 ms - 1001
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
Please provide correct steps to reproduce the issue

**Comment by lassebm** [comment]
```
from appium import webdriver

capabilities = {
    "platformName": "Mac",
    "automationName": "Mac2",
    "appium:bundleId": "com.apple.QuickTimePlayerX",
    "appium:showServerLogs": True
}

driver = webdriver.Remote(
    command_executor='http://localhost:4723/wd/hub',
    desired_capabilities=capabilities
)

driver = webdriver.Remote(
    command_executor='http://localhost:4723/wd/hub',
    desired_capabilities=capabilities
)
```

**Comment by mykola-mokhnach** [comment]
I think I know what might be causing that. Please try https://github.com/appium/appium-mac2-driver/pull/38

**Comment by lassebm** [comment]
Works like a charm, thanks @mykola-mokhnach!
