### ISSUE TITLE
Error when passing '@' letter as parameter in sendKeys

### ISSUE THREAD

**Issue by egibar** [appium/appium-mac2-driver#55]
I am trying to use appium-mac2-drive for an macOS app, but I am facing an issue when I try to log in and pass my email. It seems like the driver is not getting @ as a letter.

```
[debug] [W3C (378fa05c)] Calling AppiumDriver.execute() with args: ["macos:keys",[{"keys":["a","s","i","e","n","@","h","o","t","m","a","i","l",".","c","o","m"]}],"378fa05c-b9d6-455d-b494-34faf71b67c3"]
[Mac2Driver] Executing extension command 'macos:keys'
[debug] [WD Proxy] Proxying [POST /wda/keys] to [POST http://127.0.0.1:10100/session/431E17F1-F39A-42CA-B780-AE38E22A8388/wda/keys] with body: {"keys":["a","s","i","e","n","@","h","o","t","m","a","i","l",".","c","o","m"]}
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"Invalid parameter not satisfying: newState != nil","traceback":"(\n\t0   CoreFoundation                      0x00007fff38474b57 __exceptionPreprocess + 250\n\t1   libobjc.A.dylib                     0x00007fff712f05bf objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff3849dd08 +[NSException raise:format:arguments:] + 88\n\t3   Foundation                          0x00007fff3ab8fead -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191\n\t4   XCTest                              0x000000010ebf40e9 -[XCUIKeyboardLayout deactivateWithNewState:error:] + 377\n\t5   XCTest                              0x000000010ebfee65 __39-[XCUITextEventInterpolator invalidate]_block_invoke + 62\n\t6   CoreFoundation                      0x00007fff383f89ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t7   CoreFoundation                      0x00007fff383f8934 __CFRunLoopDoBlocks + 379\n\t8   CoreFoundation                  ...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [W3C (378fa05c)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Invalid parameter not satisfying: newState != nil
[debug] [W3C (378fa05c)]     at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [W3C (378fa05c)]     at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [W3C (378fa05c)]     at WDAMacProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[debug] [W3C (378fa05c)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[HTTP] <-- POST /wd/hub/session/378fa05c-b9d6-455d-b494-34faf71b67c3/execute/sync 500 439 ms - 815
```

**Comment by mykola-mokhnach** [comment]
Apple's documentations says:

```
/*!
 * Types a single key with the specified modifier flags. Although `key` is a string, it must represent
 * a single key on a physical keyboard; strings that resolve to multiple keys will raise an error at runtime.
 * In addition to literal string key representations like "a", "6", and "[", keys such as the arrow keys,
 * command, control, option, and function keys can be typed using constants defined for them in XCUIKeyboardKeys.h
 */
- (void)typeKey:(NSString *)key modifierFlags:(XCUIKeyModifierFlags)flags;
```

And since there is no key named `@`, I would try to type `2` with Shift modifier instead
