### ISSUE TITLE
Unable to press single button (esc) via keys actions

### ISSUE THREAD

**Issue by DmitryMishtal** [appium/appium-mac2-driver#59]
Hello community.

I'm unable to press single button with "macos: keys" action

OS: Big Sur 11.1
Xcode version: 12.4
Appium version: 1.20.2

Logs from server:

```
[HTTP] {"script":"macos: keys","args":[{"keys":["XCUIKeyboardKeyEscape"]}]}
[debug] [W3C (04cb5dd3)] Calling AppiumDriver.execute() with args: ["macos: keys",[{"keys":["XCUIKeyboardKeyEscape"]}],"04cb5dd3-3766-425c-b1e7-377ca9a55f22"]
[Mac2Driver] Executing extension command 'macos: keys'
[debug] [WD Proxy] Proxying [POST /wda/keys] to [POST http://127.0.0.1:10100/session/C64AAD18-5514-4F90-A4EA-2E498C5C9779/wda/keys] with body: {"keys":["XCUIKeyboardKeyEscape"]}
[WD Proxy] Got response with status 500: {"value":{"error":"unknown error","message":"Input key 'XCUIKeyboardKeyEscape' is too long (21 characters). Use XCUIElement.typeText for strings with more than 1 character.","traceback":"(\n\t0   CoreFoundation                      0x00007fff204df6af __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff202173c9 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff204df513 +[NSException raise:format:] + 189\n\t3   XCTest                              0x000000010104430d -[XCUIElement(XCUIElementKeyboardEvents) typeKey:modifierFlags:] + 124\n\t4   WebDriverAgentLib                   0x00000001036667a4 +[FBElementCommands handleKeys:] + 1332\n\t5   WebDriverAgentLib                   0x000000010369b976 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t6   WebDriverAgentLib                   0x00000001036952d6 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 854\n\t7   WebDriverAgentLib                   0x000000010368e3cb -[RoutingHTTPServe...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [W3C (04cb5dd3)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Input key 'XCUIKeyboardKeyEscape' is too long (21 characters). Use XCUIElement.typeText for strings with more than 1 character.
[debug] [W3C (04cb5dd3)]     at errorFromW3CJsonCode (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[debug] [W3C (04cb5dd3)]     at ProxyRequestError.getActualError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[debug] [W3C (04cb5dd3)]     at WDAMacProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[debug] [W3C (04cb5dd3)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Logs says that this is should be 'typeText' command, but currently mac2 driver unable to execute that command (as i understood)

```
Unknown extension command "typeText". Only setValue,click,scroll,rightClick,hover,doubleClick,clickAndDrag,clickAndDragAndHold,clickAndHold,keys,source,launchApp,activateApp,terminateApp,queryAppState,appleScript,startRecordingScreen,stopRecordingScreen commands are supported.
```

**Comment by mykola-mokhnach** [comment]
`typeText` is mapped to sendKeys W3C API: https://github.com/appium/appium-mac2-driver/blob/1cae6023d3b1c19f81a1ce20a007d9b29d5a004e/WebDriverAgentMac/WebDriverAgentLib/Commands/FBElementCommands.m#L143

**Comment by mykola-mokhnach** [comment]
Actually, it makes sense to add such feature to the driver to be able to type special key by providing its name.

**Comment by mykola-mokhnach** [comment]
The patch has been pushed to appium@beta

**Comment by mythsunwind** [comment]
Hi Nick 😃 

Will there be a release of java-client soon? Because the last release from November does not have the mac2-driver support in it.
