### ISSUE TITLE
When mac2 driver session isn't closed properly the WDA is left open and hogging the wdaPort

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium-mac2-driver#72]
When a session isn't cleaned up properly the WDA server is left open and will hog the assigned wdaPort. New sessions does not know how to clean this up and complains that the port is in use. 

2021-04-13 13:55:31:797 - [BaseDriver] Session created with session id: d17e6472-0a38-4222-a9d9-af429de3f7e8
2021-04-13 13:55:31:797 - [debug] [WebDriverAgentMac] Using bootstrap root: /usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/WebDriverAgentMac
2021-04-13 13:55:31:797 - [debug] [WebDriverAgentMac] Using xcodebuild binary at '/usr/bin/xcodebuild'
2021-04-13 13:55:31:798 - [WebDriverAgentMac] WebDriverAgent sources are up to date (499162500000 >= 499162500000)
2021-04-13 13:55:31:798 - [debug] [WebDriverAgentMac] Using port 10100
2021-04-13 13:55:31:798 - [WebDriverAgentMac] Mac2Driver session cannot be stopped, because the server is not running
2021-04-13 13:55:31:798 - [debug] [BaseDriver] Event 'newSessionStarted' logged at 1618347331798 (13:55:31 GMT-0700 (Pacific Daylight Time))
2021-04-13 13:55:31:799 - [debug] [W3C] Encountered internal error running command: Error: The port #10100 is busy. Consider setting 'systemPort' capability to another free port number and/or make sure the previous driver session(s) have been closed properly.
2021-04-13 13:55:31:799 - [debug] [W3C]     at WDAMacProcess.init (/usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/lib/wda-mac.js:186:13)
2021-04-13 13:55:31:799 - [debug] [W3C]     at WDAMacServer.startSession (/usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/lib/wda-mac.js:283:37)
2021-04-13 13:55:31:799 - [debug] [W3C]     at Mac2Driver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-mac2-driver/lib/driver.js:84:7)
2021-04-13 13:55:31:799 - [debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:371:35)

exec@tgtmac2:logs$ lsof -i :10100 | grep LISTEN
WebDriver 1268 exec   20u  IPv4 0x19382d730f8f1835      0t0  TCP *:itap-ddtp (LISTEN)
WebDriver 1268 exec   21u  IPv6 0x19382d7304fa46c5      0t0  TCP *:itap-ddtp (LISTEN)

The logging says that Mac2Driver isn't running, but it is very much running

**Comment by mykola-mokhnach** [comment]
This is an intended behavior. Although I've added https://github.com/appium/appium-mac2-driver/pull/73 to make it more flexible

**Comment by mykola-mokhnach** [comment]
The feature has been published to appium@beta

**Comment by Jiurong-Yang** [comment]
I see so the new behavior is that Appium will try to terminate the WDA using that port on session start up. And if the process cannot be killed then it'll error out. Sounds like it should fix the problem.
