### ISSUE TITLE
Unable to Enter text using Send key in mac catalyst app 

### ISSUE THREAD

**Issue by IshuvirSingh** [appium/appium-mac2-driver#80]
Hi Team, 

Our team developed the catalyst version of mac apps from iOS app and i am using same code base for automating its mac app application But sendkeys is not working well in Mac app .

Locator :  public String Email = "//XCUIElementTypeTextField";
code:  
driver.findElement(By.xpath(Email)).sendKeys("xty@gmail.com");

Issue: As it shows like it has entered something in field but not displayed in app itself and later it doesn't respond. Could you please help on this issue.
I have attached error from eclipse and appium logs.

Error in eclipse-->
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: 'GET /wd/hub/session/2914ssdb55-beb9-4ff4-9ce0-d52045ba6fc5/screenshot' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed). Check the Appium log for more details

Appium Log-->
```
[W3C (29146b55)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"ACA18F53-F1E6-428A-9A1E-8B3AD9FB8DD5","ELEMENT":"ACA18F53-F1E6-428A-9A1E-8B3AD9FB8DD5"}
[HTTP] <-- POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element 200 60556 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeTextField"}
[W3C (29146b55)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTextField","29146b55-beb9-4ff4-9ce0-d52045ba6fc5"]
[BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:10100/session/6FE4879D-0B52-46DC-A670-50193E19156C/element] with body: {"using":"xpath","value":"//XCUIElementTypeTextField"}
[WD Proxy] Got response with status 200: {"value":{"ELEMENT":"82267263-F15A-4244-B681-BDA8C3BAA087","element-6066-11e4-a52e-4f735466cecf":"82267263-F15A-4244-B681-BDA8C3BAA087"},"sessionId":"6FE4879D-0B52-46DC-A670-50193E19156C"}
[W3C (29146b55)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"82267263-F15A-4244-B681-BDA8C3BAA087","ELEMENT":"82267263-F15A-4244-B681-BDA8C3BAA087"}
[HTTP] <-- POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element 200 511 ms - 137
[HTTP] 
[HTTP] --> POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element/82267263-F15A-4244-B681-BDA8C3BAA087/value
[HTTP] {"id":"82267263-F15A-4244-B681-BDA8C3BAA087","text":"ui2@gmail.com","value":["u","i","2","@","g","m","a","i","l",".","c","o","m"]}
[W3C (29146b55)] Driver proxy active, passing request on via HTTP proxy
[WD Proxy] Matched '/wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element/82267263-F15A-4244-B681-BDA8C3BAA087/value' to command name 'setValue'
[WD Proxy] Proxying [POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element/82267263-F15A-4244-B681-BDA8C3BAA087/value] to [POST http://127.0.0.1:10100/session/6FE4879D-0B52-46DC-A670-50193E19156C/element/82267263-F15A-4244-B681-BDA8C3BAA087/value] with body: {"id":"82267263-F15A-4244-B681-BDA8C3BAA087","text":"ui2@gmail.com","value":["u","i","2","@","g","m","a","i","l",".","c","o","m"]}
[WD Proxy] Got response with status 200: {"value":null,"sessionId":"6FE4879D-0B52-46DC-A670-50193E19156C"}
[WD Proxy] Replacing sessionId 6FE4879D-0B52-46DC-A670-50193E19156C with 29146b55-beb9-4ff4-9ce0-d52045ba6fc5
[HTTP] <-- POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element/82267263-F15A-4244-B681-BDA8C3BAA087/value 200 9034 ms - 65
[HTTP] 
[HTTP] --> POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeSecureTextField"}
[W3C (29146b55)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeSecureTextField","29146b55-beb9-4ff4-9ce0-d52045ba6fc5"]
[BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://127.0.0.1:10100/session/6FE4879D-0B52-46DC-A670-50193E19156C/element] with body: {"using":"xpath","value":"//XCUIElementTypeSecureTextField"}
[WD Proxy] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeSecureTextField'","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000111a8ae1a FBNoSuchElementErrorResponseForRequest + 298\n\t1   WebDriverAgentLib                   0x0000000111a8ab8b +[FBFindElementCommands handleFindElement:] + 475\n\t2   WebDriverAgentLib                   0x0000000111ad1976 -[FBRoute_TargetAction mountRequest:intoResponse:] + 182\n\t3   WebDriverAgentLib                   0x0000000111acb2d6 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 854\n\t4   WebDriverAgentLib                   0x0000000111ac43cb -[RoutingHTTPServer handleRoute:withRequest:response:] + 219\n\t5   WebDriverAgentLib                   0x0000000111ac52c3 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 83\n\t6   libdispatch.dylib                   0x00007fff69f9e658 _dispatch_client_callout + 8\n\t7   libdispatch.dylib                   0...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[W3C (29146b55)] Encountered internal error running command: NoSuchElementError: unable to find an element using 'xpath', value '//XCUIElementTypeSecureTextField'
[W3C (29146b55)]     at errorFromW3CJsonCode (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
[W3C (29146b55)]     at ProxyRequestError.getActualError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
[W3C (29146b55)]     at WDAMacProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:273:19)
[W3C (29146b55)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5/element 404 318 ms - 818
[HTTP] 
[WebDriverAgentMac] Mac2Driver host process has exited with code 65, signal null
[HTTP] --> POST /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeSecureTextField"}
[W3C (29146b55)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeSecureTextField","29146b55eb9-4ff4-9ce0-d52045ba6fc5"]
[BaseDriver] Valid locator strategies for this request: id, name, accessibility id, xpath, class name, -ios predicate string, predicate string, -ios class chain, class chain
[W3C (29146b55)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed). Check the Appium log for more details
[W3C (29146b55)]     at WDAMacProxy.command (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[W3C (29146b55)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[HTTP] <-- POST /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5/element 500 3 ms - 778
[HTTP] 
[HTTP] --> GET /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5/screenshot
[HTTP] {}
[W3C (29146b55)] Driver proxy active, passing request on via HTTP proxy
[W3C (29146b55)] Encountered internal error running command: Error: Could not proxy. Proxy error: 'GET /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5/screenshot' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed). Check the Appium log for more details
[W3C (29146b55)]     at doJwpProxy (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:481:13)
[W3C (29146b55)]     at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:253:9)
[HTTP] <-- GET /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5/screenshot 500 50 ms - 1027
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/29146b55-beb9-4ff4-9ce0-d52045ba6fc5
[HTTP] {}
[W3C (29146b55)] Calling AppiumDriver.deleteSession() with args: ["291455-beb9-4ff4-9ce0-d52045ba6fc5"]
[BaseDriver] Event 'quitSessionRequested' logged at 1621699439601 (18:03:59 GMT+0200 (Central European Summer Time))
[Appium] Removing session 291455-beb9-4ff4-9ce0-d52045ba6fc5 from our master session list
[WebDriverAgentMac] Mac2Driver session cannot be stopped, because the server is not running
[BaseDriver] Event 'quitSessionFinished' logged at 1621699439602 (18:03:59 GMT+0200 (Central European Summer Time))
[W3C (29146b55)] Received response: null
[W3C (29146b55)] But deleting session, so not returning
[W3C (29146b55)] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/291465-beb9-4ff4-9ce0-d52045ba6fc5 200 1 ms - 14
[HTTP] 
```

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we could do there. Only Apple itself is able to fix such issues in XCTest. 
I would try to send keys using AppleScript or copy and paste the value as a possible workaround.
